spring:
  profiles:
    active: local
  #thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/   # .html 파일 경로 (src/main/resources/templates)
    suffix: .html   # 확장자
    cache: false # default: true, 개발 시에는 false로 두는 것이 좋음
  mvc:
    static-path-pattern: /static/** # spring mvc 정적 파일들의 경로 (css, js파일 등)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:4306/spring_db # spring_db 부분은 설정한 DB명과 맞춘다.
    username: root
    #password: password # 비밀 번호가 있을 경우 설정한다.
mybatis:
  mapper-locations:
    - classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true # (DB)value_name -> (Java)valueName 자동 매핑
server:
  servlet:
    context-path: /
  port: 8080 # 웹 서버의 포트 번호